### ISSUE TITLE
Suggestion: change cursor busy image to the one in Deepin File Manager

### ISSUE THREAD

**Issue by dwlsalmeida** [linuxdeepin/deepin-cursor-theme#1]
I mean ![](https://user-images.githubusercontent.com/11738710/48667565-dea3ed80-eab7-11e8-9e31-514e5481f9e2.png). Looks more consistent with the rest of the system

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
